module.exports = {
    /**
     * @constant {string} SUCCESS
     */
    OK: 'OK',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',

    PROFILE_UPDATE: 'PROFILE_UPDATE',
    PASSWORD_UPDATE: 'PASSWORD_UPDATE',
    SETTING_UPDATE: 'SETTING_UPDATE',

    OTP_SENDED: 'OTP_SENDED',
    OTP_VERIFIED: 'OTP_VERIFIED',

    UPLOAD_DONE: 'UPLOAD_DONE'
};